---
- name: Ensure that the postfix packages are installed
  tags: postfix
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: postfix_yum
  with_items:
    - postfix
    - "{{ postfix_packages }}"

- name: Attempting to import postfix configuration tasks
  tags: postfix
  become: true
  block:
    - import_tasks: postfix_version.yml
    - import_tasks: postfix_configuration.yml
    - import_tasks: postfix_service.yml
  when: postfix_yum is success
...
