---
- name: Ensure that the postfix packages are installed
  tags: postfix
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: postfix_yum
  with_items:
    - postfix
    - "{{ postfix_packages }}"

- block:
    - name: Applying postfix configurations
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      notify: restart postfix
      with_items:
        - { src: main.cf.j2, dest: /etc/postfix/main.cf, mode: '0644' }

    - name: Enable and start the postfix service on boot
      service:
        enabled: yes
        name: postfix
        state: started
  tags: postfix
  become: true
  when: postfix_yum|success
...
